function [res, jsonStr] = process_image(imagePath, cfg)
% PROCESS_IMAGE Primary entry point for Task 1: Retinal Image Quality Check & Preprocessing.
%
% Syntax:
%   [res, jsonStr] = process_image(imagePath, cfg)
%
% Inputs:
%   imagePath - Path to the raw retinal fundus image
%   cfg       - (Optional) System configuration struct
%
% Outputs:
%   res       - Result MATLAB struct containing quality assessment, action, and paths
%   jsonStr   - Standardized JSON string representation
%
% Clinical Quality Gate Logic:
%   1. If quality is UNGRADABLE (score < 30% or blur/exposure fail):
%      quality_status = "ungradable", action = "Recapture image", recapture_required = true.
%      Prompt: "Please capture/upload another retinal image."
%      Diagnostic inference is HALTED.
%   2. If quality is ACCEPTABLE (score >= 30%):
%      Proceeds with Homomorphic Normalization, Bilateral Denoising, and CLAHE.

    if nargin < 2 || isempty(cfg)
        cfg = config_params();
    end

    normalizedInputPath = string(strrep(imagePath, '\', '/'));

    if ~exist(imagePath, 'file')
        res = struct(...
            'image_path', normalizedInputPath, ...
            'quality_status', "ungradable", ...
            'quality_score', 0.0, ...
            'action', "Recapture image", ...
            'recapture_required', true, ...
            'message', sprintf("Image file not found: '%s'. Please select a valid retinal fundus image.", imagePath) ...
        );
        jsonStr = jsonencode(res, 'PrettyPrint', true);
        return;
    end

    try
        img = imread(imagePath);
    catch ME
        res = struct(...
            'image_path', normalizedInputPath, ...
            'quality_status', "ungradable", ...
            'quality_score', 0.0, ...
            'action', "Recapture image", ...
            'recapture_required', true, ...
            'message', sprintf("Failed to decode image: %s. Please upload an intact image file.", ME.message) ...
        );
        jsonStr = jsonencode(res, 'PrettyPrint', true);
        return;
    end

    if ndims(img) == 2
        img = cat(3, img, img, img);
    end

    % 1. Evaluate Retinal Quality
    [qualityStatus, qualityScore, failureReason, metrics] = check_quality(img, cfg);

    % 2. Quality Gate Decision
    if qualityStatus == "ungradable"
        res = struct(...
            'image_path', normalizedInputPath, ...
            'quality_status', "ungradable", ...
            'quality_score', qualityScore, ...
            'action', "Recapture image", ...
            'recapture_required', true, ...
            'reason', failureReason, ...
            'message', sprintf("Image quality is too low: %s. Please capture/upload another retinal image.", failureReason), ...
            'metrics', metrics ...
        );
    else
        isBorderline = metrics.isBorderline;
        try
            enhancedPath = enhance_fundus_image(img, imagePath, cfg.OUTPUT_ENHANCED, isBorderline);

            if isBorderline
                qualityGrade = sprintf("borderline (%d%% quality - adaptive enhancement applied)", round(qualityScore * 100));
                action = "enhanced";
                msg = sprintf("Borderline image quality (%d%%). Adaptive homomorphic enhancement and sharpening applied. Diagnostic review advised.", round(qualityScore * 100));
            else
                qualityGrade = sprintf("optimal (%d%% quality)", round(qualityScore * 100));
                action = "proceed";
                msg = "Image quality is optimal for AI diagnostic grading.";
            end

            res = struct(...
                'image_path', string(enhancedPath), ...
                'original_path', normalizedInputPath, ...
                'quality_status', "acceptable", ...
                'quality_score', qualityScore, ...
                'quality_grade', qualityGrade, ...
                'action', action, ...
                'recapture_required', false, ...
                'message', msg, ...
                'metrics', metrics ...
            );
        catch ME
            res = struct(...
                'image_path', normalizedInputPath, ...
                'quality_status', "ungradable", ...
                'quality_score', qualityScore, ...
                'action', "Recapture image", ...
                'recapture_required', true, ...
                'reason', sprintf("Enhancement failure: %s", ME.message), ...
                'message', "Internal error during enhancement. Please capture/upload another retinal image.", ...
                'metrics', metrics ...
            );
        end
    end

    jsonStr = jsonencode(res, 'PrettyPrint', true);
end
